/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class transaq_TransaqConnector */

#ifndef _Included_transaq_TransaqConnector
#define _Included_transaq_TransaqConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     transaq_TransaqConnector
 * Method:    GetServiceInfo
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_transaq_TransaqConnector_GetServiceInfo
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     transaq_TransaqConnector
 * Method:    Initialize
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_Initialize
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     transaq_TransaqConnector
 * Method:    SetLogLevel
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_SetLogLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     transaq_TransaqConnector
 * Method:    SendCommand
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_SendCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     transaq_TransaqConnector
 * Method:    UnInitialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_UnInitialize
  (JNIEnv *, jobject);

/*
 * Class:     transaq_TransaqConnector
 * Method:    LoadDllTransaq
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_LoadDllTransaq
  (JNIEnv *, jobject);

/*
 * Class:     transaq_TransaqConnector
 * Method:    UnLoadDllTransaq
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_UnLoadDllTransaq
  (JNIEnv *, jobject);

/*
 * Class:     transaq_TransaqConnector
 * Method:    SetCallback
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_transaq_TransaqConnector_SetCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
