//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 02:08:38 PM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trade" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tradeno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trade"
})
@XmlRootElement(name = "alltrades")
public class Alltrades {

    protected List<Alltrades.Trade> trade;

    /**
     * Gets the value of the trade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alltrades.Trade }
     * 
     * 
     */
    public List<Alltrades.Trade> getTrade() {
        if (trade == null) {
            trade = new ArrayList<Alltrades.Trade>();
        }
        return this.trade;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tradeno" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seccode",
        "tradeno",
        "time",
        "board",
        "price",
        "quantity",
        "buysell",
        "openinterest",
        "period"
    })
    public static class Trade {

        @XmlElement(required = true)
        protected String seccode;
        protected int tradeno;
        @XmlElement(required = true)
        protected String time;
        @XmlElement(required = true)
        protected String board;
        @XmlElement(required = true)
        protected BigDecimal price;
        protected int quantity;
        @XmlElement(required = true)
        protected String buysell;
        protected int openinterest;
        @XmlElement(required = true)
        protected String period;
        @XmlAttribute(name = "secid")
        protected Integer secid;

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the tradeno property.
         * 
         */
        public int getTradeno() {
            return tradeno;
        }

        /**
         * Sets the value of the tradeno property.
         * 
         */
        public void setTradeno(int value) {
            this.tradeno = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the buysell property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuysell() {
            return buysell;
        }

        /**
         * Sets the value of the buysell property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuysell(String value) {
            this.buysell = value;
        }

        /**
         * Gets the value of the openinterest property.
         * 
         */
        public int getOpeninterest() {
            return openinterest;
        }

        /**
         * Sets the value of the openinterest property.
         * 
         */
        public void setOpeninterest(int value) {
            this.openinterest = value;
        }

        /**
         * Gets the value of the period property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriod(String value) {
            this.period = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSecid(Integer value) {
            this.secid = value;
        }

    }

}
