//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 02:08:38 PM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trade" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tradeno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trade"
})
@XmlRootElement(name = "alltrades")
public class Alltrades {

    protected List<Alltrades.Trade> trade;

    /**
     * Gets the value of the trade property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trade property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrade().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alltrades.Trade }
     * 
     * 
     */
    public List<Alltrades.Trade> getTrade() {
        if (trade == null) {
            trade = new ArrayList<Alltrades.Trade>();
        }
        return this.trade;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tradeno" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seccode",
        "tradeno",
        "time",
        "board",
        "price",
        "quantity",
        "buysell",
        "openinterest",
        "period"
    })
    public static class Trade {

        @XmlElement(required = true)
        protected String seccode;
        protected int tradeno;
        @XmlElement(required = true)
                //04.06.2019 16:03:13.279
        @XmlJavaTypeAdapter(Trades.DateAdapter.class)
        protected Date time;
        @XmlElement(required = true)
        protected String board;
        @XmlElement(required = true)
        protected BigDecimal price;
        protected int quantity;
        @XmlElement(required = true)
        protected String buysell;
        protected int openinterest;
        @XmlElement(required = true)
        protected String period;
        @XmlAttribute(name = "secid")
        protected Integer secid;
        
        @XmlTransient
        private BigDecimal  averagePrice;
        @XmlTransient
        private BigDecimal  standardDeviation;
        @XmlTransient
        private BigDecimal  minPrice;
        @XmlTransient
        private BigDecimal  maxPrice;
        
        
        @XmlTransient
        private Integer  allQuantityOfPurchased;
        @XmlTransient
        private Integer  allQuantitySold;        
        @XmlTransient    
        private BigDecimal  allAmountSold;
        @XmlTransient
        private BigDecimal  allPurchasesAmount;
        @XmlTransient    
        private BigDecimal  averageSoldPrice;
        @XmlTransient
        private BigDecimal  averageBuyingPrice;        
        @XmlTransient    
        private BigDecimal  allAmountSellingAndBuying;
        @XmlTransient
        private Integer  sellingAndBuyingQuantityAll; 
        @XmlTransient    
        private BigDecimal  averageBuyingAndSellingPrice;  
        
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesBuy1;
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesSell1;
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesBuy2;
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesSell2;
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesBuy3;
        @XmlTransient    
        private BigDecimal  theRateOfChangeOfPricesSell3;        

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the tradeno property.
         * 
         */
        public int getTradeno() {
            return tradeno;
        }

        /**
         * Sets the value of the tradeno property.
         * 
         */
        public void setTradeno(int value) {
            this.tradeno = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(Date value) {
            this.time = value;
        }

        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the buysell property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuysell() {
            return buysell;
        }

        /**
         * Sets the value of the buysell property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuysell(String value) {
            this.buysell = value;
        }

        /**
         * Gets the value of the openinterest property.
         * 
         */
        public int getOpeninterest() {
            return openinterest;
        }

        /**
         * Sets the value of the openinterest property.
         * 
         */
        public void setOpeninterest(int value) {
            this.openinterest = value;
        }

        /**
         * Gets the value of the period property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriod(String value) {
            this.period = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSecid(Integer value) {
            this.secid = value;
        }

        public BigDecimal getAveragePrice() {
            return averagePrice;
        }

        public void setAveragePrice(BigDecimal averagePrice) {
            this.averagePrice = averagePrice;
        }

        public BigDecimal getStandardDeviation() {
            return standardDeviation;
        }

        public void setStandardDeviation(BigDecimal standardDeviation) {
            this.standardDeviation = standardDeviation;
        }

        public BigDecimal getMinPrice() {
            return minPrice;
        }

        public void setMinPrice(BigDecimal minPrice) {
            this.minPrice = minPrice;
        }

        public BigDecimal getMaxPrice() {
            return maxPrice;
        }

        public void setMaxPrice(BigDecimal maxPrice) {
            this.maxPrice = maxPrice;
        }

        public Integer getAllQuantityOfPurchased() {
            return allQuantityOfPurchased;
        }

        public void setAllQuantityOfPurchased(Integer allQuantityOfPurchased) {
            this.allQuantityOfPurchased = allQuantityOfPurchased;
        }

        public Integer getAllQuantitySold() {
            return allQuantitySold;
        }

        public void setAllQuantitySold(Integer allQuantitySold) {
            this.allQuantitySold = allQuantitySold;
        }

        public BigDecimal getAllAmountSold() {
            return allAmountSold;
        }

        public void setAllAmountSold(BigDecimal allAmountSold) {
            this.allAmountSold = allAmountSold;
        }

        public BigDecimal getAllPurchasesAmount() {
            return allPurchasesAmount;
        }

        public void setAllPurchasesAmount(BigDecimal allPurchasesAmount) {
            this.allPurchasesAmount = allPurchasesAmount;
        }

        public BigDecimal getAverageSoldPrice() {
            return averageSoldPrice;
        }

        public void setAverageSoldPrice(BigDecimal averageSoldPrice) {
            this.averageSoldPrice = averageSoldPrice;
        }

        public BigDecimal getAverageBuyingPrice() {
            return averageBuyingPrice;
        }

        public void setAverageBuyingPrice(BigDecimal averageBuyingPrice) {
            this.averageBuyingPrice = averageBuyingPrice;
        }

        public BigDecimal getAllAmountSellingAndBuying() {
            return allAmountSellingAndBuying;
        }

        public void setAllAmountSellingAndBuying(BigDecimal allAmountSellingAndBuying) {
            this.allAmountSellingAndBuying = allAmountSellingAndBuying;
        }

        public Integer getSellingAndBuyingQuantityAll() {
            return sellingAndBuyingQuantityAll;
        }

        public void setSellingAndBuyingQuantityAll(Integer sellingAndBuyingQuantityAll) {
            this.sellingAndBuyingQuantityAll = sellingAndBuyingQuantityAll;
        }

        public BigDecimal getAverageBuyingAndSellingPrice() {
            return averageBuyingAndSellingPrice;
        }

        public void setAverageBuyingAndSellingPrice(BigDecimal averageBuyingAndSellingPrice) {
            this.averageBuyingAndSellingPrice = averageBuyingAndSellingPrice;
        }

        public BigDecimal getTheRateOfChangeOfPricesBuy1() {
            return theRateOfChangeOfPricesBuy1;
        }

        public void setTheRateOfChangeOfPricesBuy1(BigDecimal theRateOfChangeOfPricesBuy1) {
            this.theRateOfChangeOfPricesBuy1 = theRateOfChangeOfPricesBuy1;
        }

        public BigDecimal getTheRateOfChangeOfPricesSell1() {
            return theRateOfChangeOfPricesSell1;
        }

        public void setTheRateOfChangeOfPricesSell1(BigDecimal theRateOfChangeOfPricesSell1) {
            this.theRateOfChangeOfPricesSell1 = theRateOfChangeOfPricesSell1;
        }

        public BigDecimal getTheRateOfChangeOfPricesBuy2() {
            return theRateOfChangeOfPricesBuy2;
        }

        public void setTheRateOfChangeOfPricesBuy2(BigDecimal theRateOfChangeOfPricesBuy2) {
            this.theRateOfChangeOfPricesBuy2 = theRateOfChangeOfPricesBuy2;
        }

        public BigDecimal getTheRateOfChangeOfPricesSell2() {
            return theRateOfChangeOfPricesSell2;
        }

        public void setTheRateOfChangeOfPricesSell2(BigDecimal theRateOfChangeOfPricesSell2) {
            this.theRateOfChangeOfPricesSell2 = theRateOfChangeOfPricesSell2;
        }

        public BigDecimal getTheRateOfChangeOfPricesBuy3() {
            return theRateOfChangeOfPricesBuy3;
        }

        public void setTheRateOfChangeOfPricesBuy3(BigDecimal theRateOfChangeOfPricesBuy3) {
            this.theRateOfChangeOfPricesBuy3 = theRateOfChangeOfPricesBuy3;
        }

        public BigDecimal getTheRateOfChangeOfPricesSell3() {
            return theRateOfChangeOfPricesSell3;
        }

        public void setTheRateOfChangeOfPricesSell3(BigDecimal theRateOfChangeOfPricesSell3) {
            this.theRateOfChangeOfPricesSell3 = theRateOfChangeOfPricesSell3;
        }


        
       

    }
    
    public static class DateAdapter extends XmlAdapter<String, Date> {
////04.06.2019 16:03:13.279
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss.SSS");

    @Override
    public String marshal(Date v) throws Exception {
        synchronized (dateFormat) {
            return dateFormat.format(v);
        }
    }

    @Override
    public Date unmarshal(String v) throws Exception {
        synchronized (dateFormat) {
            return dateFormat.parse(v);
        }
    }

}

}
