//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 12:32:09 PM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="candle" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="open" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="close" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="oi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="board" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seccode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="period" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "candle"
})
@XmlRootElement(name = "candles")
public class Candles {

    protected List<Candles.Candle> candle;
    @XmlAttribute(name = "secid")
    protected Short secid;
    @XmlAttribute(name = "board")
    protected String board;
    @XmlAttribute(name = "seccode")
    protected String seccode;
    @XmlAttribute(name = "period")
    protected Byte period;
    @XmlAttribute(name = "status")
    protected Byte status;

    /**
     * Gets the value of the candle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the candle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCandle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Candles.Candle }
     * 
     * 
     */
    public List<Candles.Candle> getCandle() {
        if (candle == null) {
            candle = new ArrayList<Candles.Candle>();
        }
        return this.candle;
    }

    /**
     * Gets the value of the secid property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSecid() {
        return secid;
    }

    /**
     * Sets the value of the secid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSecid(Short value) {
        this.secid = value;
    }

    /**
     * Gets the value of the board property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoard() {
        return board;
    }

    /**
     * Sets the value of the board property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoard(String value) {
        this.board = value;
    }

    /**
     * Gets the value of the seccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeccode() {
        return seccode;
    }

    /**
     * Sets the value of the seccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeccode(String value) {
        this.seccode = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPeriod(Byte value) {
        this.period = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setStatus(Byte value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="open" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="close" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="high" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="oi" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="low" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Candle {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "date")
               //04.06.2019 16:03:13.279
        @XmlJavaTypeAdapter(Trades.DateAdapter.class)
        protected Date date;
        @XmlAttribute(name = "open")
        protected BigDecimal open;
        @XmlAttribute(name = "close")
        protected BigDecimal close;
        @XmlAttribute(name = "high")
        protected BigDecimal high;
        @XmlAttribute(name = "oi")
        protected Integer oi;
        @XmlAttribute(name = "low")
        protected BigDecimal low;
        @XmlAttribute(name = "volume")
        protected Integer volume;
        
        @XmlTransient
        protected BigDecimal bAveragePrice;
        @XmlTransient
        protected BigDecimal bDeviationPrice;
        @XmlTransient
        protected BigDecimal bMaxPrice; 
        @XmlTransient
        protected BigDecimal bMinPrice;
        @XmlTransient
        protected BigDecimal priceChangeSpeed;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the open property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public BigDecimal getOpen() {
            return open;
        }

        /**
         * Sets the value of the open property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setOpen(BigDecimal value) {
            this.open = value;
        }

        /**
         * Gets the value of the close property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public BigDecimal getClose() {
            return close;
        }

        /**
         * Sets the value of the close property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setClose(BigDecimal value) {
            this.close = value;
        }

        /**
         * Gets the value of the high property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public BigDecimal getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setHigh(BigDecimal value) {
            this.high = value;
        }

        /**
         * Gets the value of the oi property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getOi() {
            return oi;
        }

        /**
         * Sets the value of the oi property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setOi(Integer value) {
            this.oi = value;
        }

        /**
         * Gets the value of the low property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public BigDecimal getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLow(BigDecimal value) {
            this.low = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Integer getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setVolume(Integer value) {
            this.volume = value;
        }

        public BigDecimal getbAveragePrice() {
            return bAveragePrice;
        }

        public void setbAveragePrice(BigDecimal bAveragePrice) {
            this.bAveragePrice = bAveragePrice;
        }

        public BigDecimal getbDeviationPrice() {
            return bDeviationPrice;
        }

        public void setbDeviationPrice(BigDecimal bDeviationPrice) {
            this.bDeviationPrice = bDeviationPrice;
        }

        public BigDecimal getbMaxPrice() {
            return bMaxPrice;
        }

        public void setbMaxPrice(BigDecimal bMaxPrice) {
            this.bMaxPrice = bMaxPrice;
        }

        public BigDecimal getbMinPrice() {
            return bMinPrice;
        }

        public void setbMinPrice(BigDecimal bMinPrice) {
            this.bMinPrice = bMinPrice;
        }

        public BigDecimal getPriceChangeSpeed() {
            return priceChangeSpeed;
        }

        public void setPriceChangeSpeed(BigDecimal priceChangeSpeed) {
            this.priceChangeSpeed = priceChangeSpeed;
        }
        
        

    }
    
    public static class DateAdapter extends XmlAdapter<String, Date> {
////04.06.2019 16:03:13.279
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss.SSS");

    @Override
    public String marshal(Date v) throws Exception {
        synchronized (dateFormat) {
            return dateFormat.format(v);
        }
    }

    @Override
    public Date unmarshal(String v) throws Exception {
        synchronized (dateFormat) {
            return dateFormat.parse(v);
        }
    }

}

}
