//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:02:22 PM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="orderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="secid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="union" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="origin_orderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="accepttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="accruedint" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="settlecode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="withdrawtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="conditionvalue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="validafter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="validbefore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maxcomission" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="transactionid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stoporder" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="activeorderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="secid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="canceller" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="alltradeno" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="validbefore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accepttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="linkedorderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stoploss">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="orderprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="takeprofit">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="extremum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="guardspread" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="withdrawtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="transactionid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "order",
    "stoporder"
})
@XmlRootElement(name = "orders")
public class Orders {

    protected List<Orders.Order> order;
    protected List<Orders.Stoporder> stoporder;

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Orders.Order }
     * 
     * 
     */
    public List<Orders.Order> getOrder() {
        if (order == null) {
            order = new ArrayList<Orders.Order>();
        }
        return this.order;
    }

    /**
     * Gets the value of the stoporder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stoporder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoporder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Orders.Stoporder }
     * 
     * 
     */
    public List<Orders.Stoporder> getStoporder() {
        if (stoporder == null) {
            stoporder = new ArrayList<Orders.Stoporder>();
        }
        return this.stoporder;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="orderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="secid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="union" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="origin_orderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="accepttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="accruedint" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="settlecode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="withdrawtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="conditionvalue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="validafter" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="validbefore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maxcomission" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="transactionid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderno",
        "secid",
        "board",
        "seccode",
        "client",
        "union",
        "status",
        "buysell",
        "time",
        "expdate",
        "originOrderno",
        "accepttime",
        "brokerref",
        "value",
        "accruedint",
        "settlecode",
        "balance",
        "price",
        "quantity",
        "hidden",
        "yield",
        "withdrawtime",
        "condition",
        "conditionvalue",
        "validafter",
        "validbefore",
        "maxcomission",
        "result"
    })
    public static class Order {

        protected long orderno;
        protected int secid;
        @XmlElement(required = true)
        protected String board;
        @XmlElement(required = true)
        protected String seccode;
        @XmlElement(required = true)
        protected String client;
        @XmlElement(required = true)
        protected String union;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected String buysell;
        @XmlElement(required = true)
        protected String time;
        @XmlElement(required = true)
        protected String expdate;
        @XmlElement(name = "origin_orderno")
        protected long originOrderno;
        @XmlElement(required = true)
        protected String accepttime;
        @XmlElement(required = true)
        protected String brokerref;
        @XmlElement(required = true)
        protected BigDecimal value;
        @XmlElement(required = true)
        protected BigDecimal accruedint;
        @XmlElement(required = true)
        protected String settlecode;
        protected int balance;
        @XmlElement(required = true)
        protected BigDecimal price;
        protected int quantity;
        protected int hidden;
        @XmlElement(required = true)
        protected BigDecimal yield;
        @XmlElement(required = true)
        protected String withdrawtime;
        @XmlElement(required = true)
        protected String condition;
        @XmlElement(required = true)
        protected BigDecimal conditionvalue;
        @XmlElement(required = true)
        protected String validafter;
        @XmlElement(required = true)
        protected String validbefore;
        @XmlElement(required = true)
        protected BigDecimal maxcomission;
        @XmlElement(required = true)
        protected String result;
        @XmlAttribute(name = "transactionid")
        protected Integer transactionid;

        /**
         * Gets the value of the orderno property.
         * 
         */
        public long getOrderno() {
            return orderno;
        }

        /**
         * Sets the value of the orderno property.
         * 
         */
        public void setOrderno(long value) {
            this.orderno = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         */
        public int getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         */
        public void setSecid(int value) {
            this.secid = value;
        }

        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the client property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClient() {
            return client;
        }

        /**
         * Sets the value of the client property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClient(String value) {
            this.client = value;
        }

        /**
         * Gets the value of the union property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnion() {
            return union;
        }

        /**
         * Sets the value of the union property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnion(String value) {
            this.union = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the buysell property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuysell() {
            return buysell;
        }

        /**
         * Sets the value of the buysell property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuysell(String value) {
            this.buysell = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the expdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpdate() {
            return expdate;
        }

        /**
         * Sets the value of the expdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpdate(String value) {
            this.expdate = value;
        }

        /**
         * Gets the value of the originOrderno property.
         * 
         */
        public long getOriginOrderno() {
            return originOrderno;
        }

        /**
         * Sets the value of the originOrderno property.
         * 
         */
        public void setOriginOrderno(long value) {
            this.originOrderno = value;
        }

        /**
         * Gets the value of the accepttime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccepttime() {
            return accepttime;
        }

        /**
         * Sets the value of the accepttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccepttime(String value) {
            this.accepttime = value;
        }

        /**
         * Gets the value of the brokerref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrokerref() {
            return brokerref;
        }

        /**
         * Sets the value of the brokerref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrokerref(String value) {
            this.brokerref = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the accruedint property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAccruedint() {
            return accruedint;
        }

        /**
         * Sets the value of the accruedint property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAccruedint(BigDecimal value) {
            this.accruedint = value;
        }

        /**
         * Gets the value of the settlecode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSettlecode() {
            return settlecode;
        }

        /**
         * Sets the value of the settlecode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSettlecode(String value) {
            this.settlecode = value;
        }

        /**
         * Gets the value of the balance property.
         * 
         */
        public int getBalance() {
            return balance;
        }

        /**
         * Sets the value of the balance property.
         * 
         */
        public void setBalance(int value) {
            this.balance = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the hidden property.
         * 
         */
        public int getHidden() {
            return hidden;
        }

        /**
         * Sets the value of the hidden property.
         * 
         */
        public void setHidden(int value) {
            this.hidden = value;
        }

        /**
         * Gets the value of the yield property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getYield() {
            return yield;
        }

        /**
         * Sets the value of the yield property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setYield(BigDecimal value) {
            this.yield = value;
        }

        /**
         * Gets the value of the withdrawtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWithdrawtime() {
            return withdrawtime;
        }

        /**
         * Sets the value of the withdrawtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWithdrawtime(String value) {
            this.withdrawtime = value;
        }

        /**
         * Gets the value of the condition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Sets the value of the condition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCondition(String value) {
            this.condition = value;
        }

        /**
         * Gets the value of the conditionvalue property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getConditionvalue() {
            return conditionvalue;
        }

        /**
         * Sets the value of the conditionvalue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setConditionvalue(BigDecimal value) {
            this.conditionvalue = value;
        }

        /**
         * Gets the value of the validafter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidafter() {
            return validafter;
        }

        /**
         * Sets the value of the validafter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidafter(String value) {
            this.validafter = value;
        }

        /**
         * Gets the value of the validbefore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidbefore() {
            return validbefore;
        }

        /**
         * Sets the value of the validbefore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidbefore(String value) {
            this.validbefore = value;
        }

        /**
         * Gets the value of the maxcomission property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMaxcomission() {
            return maxcomission;
        }

        /**
         * Sets the value of the maxcomission property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMaxcomission(BigDecimal value) {
            this.maxcomission = value;
        }

        /**
         * Gets the value of the result property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResult(String value) {
            this.result = value;
        }

        /**
         * Gets the value of the transactionid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTransactionid() {
            return transactionid;
        }

        /**
         * Sets the value of the transactionid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTransactionid(Integer value) {
            this.transactionid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="activeorderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="secid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="buysell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="canceller" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="alltradeno" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="validbefore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accepttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="linkedorderno" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stoploss">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="orderprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="takeprofit">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="extremum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="guardspread" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="withdrawtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="transactionid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activeorderno",
        "secid",
        "board",
        "seccode",
        "client",
        "buysell",
        "canceller",
        "alltradeno",
        "validbefore",
        "author",
        "accepttime",
        "linkedorderno",
        "expdate",
        "status",
        "stoploss",
        "takeprofit",
        "withdrawtime",
        "result"
    })
    public static class Stoporder {

        protected long activeorderno;
        protected int secid;
        protected int board;
        @XmlElement(required = true)
        protected String seccode;
        @XmlElement(required = true)
        protected String client;
        @XmlElement(required = true)
        protected String buysell;
        @XmlElement(required = true)
        protected String canceller;
        protected short alltradeno;
        @XmlElement(required = true)
        protected String validbefore;
        @XmlElement(required = true)
        protected String author;
        @XmlElement(required = true)
        protected String accepttime;
        protected long linkedorderno;
        @XmlElement(required = true)
        protected String expdate;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected Orders.Stoporder.Stoploss stoploss;
        @XmlElement(required = true)
        protected Orders.Stoporder.Takeprofit takeprofit;
        @XmlElement(required = true)
        protected String withdrawtime;
        @XmlElement(required = true)
        protected String result;
        @XmlAttribute(name = "transactionid")
        protected String transactionid;

        /**
         * Gets the value of the activeorderno property.
         * 
         */
        public long getActiveorderno() {
            return activeorderno;
        }

        /**
         * Sets the value of the activeorderno property.
         * 
         */
        public void setActiveorderno(long value) {
            this.activeorderno = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         */
        public int getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         */
        public void setSecid(int value) {
            this.secid = value;
        }

        /**
         * Gets the value of the board property.
         * 
         */
        public int getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         */
        public void setBoard(int value) {
            this.board = value;
        }

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the client property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClient() {
            return client;
        }

        /**
         * Sets the value of the client property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClient(String value) {
            this.client = value;
        }

        /**
         * Gets the value of the buysell property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuysell() {
            return buysell;
        }

        /**
         * Sets the value of the buysell property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuysell(String value) {
            this.buysell = value;
        }

        /**
         * Gets the value of the canceller property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCanceller() {
            return canceller;
        }

        /**
         * Sets the value of the canceller property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCanceller(String value) {
            this.canceller = value;
        }

        /**
         * Gets the value of the alltradeno property.
         * 
         */
        public short getAlltradeno() {
            return alltradeno;
        }

        /**
         * Sets the value of the alltradeno property.
         * 
         */
        public void setAlltradeno(short value) {
            this.alltradeno = value;
        }

        /**
         * Gets the value of the validbefore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidbefore() {
            return validbefore;
        }

        /**
         * Sets the value of the validbefore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidbefore(String value) {
            this.validbefore = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the accepttime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccepttime() {
            return accepttime;
        }

        /**
         * Sets the value of the accepttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccepttime(String value) {
            this.accepttime = value;
        }

        /**
         * Gets the value of the linkedorderno property.
         * 
         */
        public long getLinkedorderno() {
            return linkedorderno;
        }

        /**
         * Sets the value of the linkedorderno property.
         * 
         */
        public void setLinkedorderno(long value) {
            this.linkedorderno = value;
        }

        /**
         * Gets the value of the expdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpdate() {
            return expdate;
        }

        /**
         * Sets the value of the expdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpdate(String value) {
            this.expdate = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the stoploss property.
         * 
         * @return
         *     possible object is
         *     {@link Orders.Stoporder.Stoploss }
         *     
         */
        public Orders.Stoporder.Stoploss getStoploss() {
            return stoploss;
        }

        /**
         * Sets the value of the stoploss property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orders.Stoporder.Stoploss }
         *     
         */
        public void setStoploss(Orders.Stoporder.Stoploss value) {
            this.stoploss = value;
        }

        /**
         * Gets the value of the takeprofit property.
         * 
         * @return
         *     possible object is
         *     {@link Orders.Stoporder.Takeprofit }
         *     
         */
        public Orders.Stoporder.Takeprofit getTakeprofit() {
            return takeprofit;
        }

        /**
         * Sets the value of the takeprofit property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orders.Stoporder.Takeprofit }
         *     
         */
        public void setTakeprofit(Orders.Stoporder.Takeprofit value) {
            this.takeprofit = value;
        }

        /**
         * Gets the value of the withdrawtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWithdrawtime() {
            return withdrawtime;
        }

        /**
         * Sets the value of the withdrawtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWithdrawtime(String value) {
            this.withdrawtime = value;
        }

        /**
         * Gets the value of the result property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResult(String value) {
            this.result = value;
        }

        /**
         * Gets the value of the transactionid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionid() {
            return transactionid;
        }

        /**
         * Sets the value of the transactionid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionid(String value) {
            this.transactionid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="orderprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *       &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "activationprice",
            "guardtime",
            "brokerref",
            "quantity",
            "orderprice"
        })
        public static class Stoploss {

            @XmlElement(required = true)
            protected BigDecimal activationprice;
            @XmlElement(required = true)
            protected String guardtime;
            @XmlElement(required = true)
            protected String brokerref;
            @XmlElement(required = true)
            protected BigDecimal quantity;
            @XmlElement(required = true)
            protected BigDecimal orderprice;
            @XmlAttribute(name = "usecredit")
            protected String usecredit;

            /**
             * Gets the value of the activationprice property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivationprice() {
                return activationprice;
            }

            /**
             * Sets the value of the activationprice property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivationprice(BigDecimal value) {
                this.activationprice = value;
            }

            /**
             * Gets the value of the guardtime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuardtime() {
                return guardtime;
            }

            /**
             * Sets the value of the guardtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuardtime(String value) {
                this.guardtime = value;
            }

            /**
             * Gets the value of the brokerref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrokerref() {
                return brokerref;
            }

            /**
             * Sets the value of the brokerref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrokerref(String value) {
                this.brokerref = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantity(BigDecimal value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the orderprice property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getOrderprice() {
                return orderprice;
            }

            /**
             * Sets the value of the orderprice property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setOrderprice(BigDecimal value) {
                this.orderprice = value;
            }

            /**
             * Gets the value of the usecredit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsecredit() {
                return usecredit;
            }

            /**
             * Sets the value of the usecredit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsecredit(String value) {
                this.usecredit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="activationprice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="guardtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="brokerref" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="extremum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="guardspread" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "activationprice",
            "guardtime",
            "brokerref",
            "quantity",
            "extremum",
            "level",
            "correction",
            "guardspread"
        })
        public static class Takeprofit {

            @XmlElement(required = true)
            protected BigDecimal activationprice;
            @XmlElement(required = true)
            protected String guardtime;
            @XmlElement(required = true)
            protected String brokerref;
            @XmlElement(required = true)
            protected BigDecimal quantity;
            @XmlElement(required = true)
            protected BigDecimal extremum;
            @XmlElement(required = true)
            protected BigDecimal level;
            @XmlElement(required = true)
            protected BigDecimal correction;
            @XmlElement(required = true)
            protected BigDecimal guardspread;

            /**
             * Gets the value of the activationprice property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getActivationprice() {
                return activationprice;
            }

            /**
             * Sets the value of the activationprice property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setActivationprice(BigDecimal value) {
                this.activationprice = value;
            }

            /**
             * Gets the value of the guardtime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuardtime() {
                return guardtime;
            }

            /**
             * Sets the value of the guardtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuardtime(String value) {
                this.guardtime = value;
            }

            /**
             * Gets the value of the brokerref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrokerref() {
                return brokerref;
            }

            /**
             * Sets the value of the brokerref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrokerref(String value) {
                this.brokerref = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setQuantity(BigDecimal value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the extremum property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getExtremum() {
                return extremum;
            }

            /**
             * Sets the value of the extremum property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setExtremum(BigDecimal value) {
                this.extremum = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLevel() {
                return level;
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLevel(BigDecimal value) {
                this.level = value;
            }

            /**
             * Gets the value of the correction property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getCorrection() {
                return correction;
            }

            /**
             * Sets the value of the correction property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setCorrection(BigDecimal value) {
                this.correction = value;
            }

            /**
             * Gets the value of the guardspread property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getGuardspread() {
                return guardspread;
            }

            /**
             * Sets the value of the guardspread property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setGuardspread(BigDecimal value) {
                this.guardspread = value;
            }

        }

    }

}
