//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 11:29:55 AM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pit" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="decimals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="minstep" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="lotsize" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="point_cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="seccode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="board" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pit"
})
@XmlRootElement(name = "pits")
public class Pits {

    @XmlElement(required = true)
    protected List<Pits.Pit> pit;

    /**
     * Gets the value of the pit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pits.Pit }
     * 
     * 
     */
    public List<Pits.Pit> getPit() {
        if (pit == null) {
            pit = new ArrayList<Pits.Pit>();
        }
        return this.pit;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="decimals" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="minstep" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="lotsize" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *         &lt;element name="point_cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *       &lt;attribute name="seccode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="board" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "market",
        "decimals",
        "minstep",
        "lotsize",
        "pointCost"
    })
    public static class Pit {

        @XmlSchemaType(name = "unsignedByte")
        protected short market;
        @XmlSchemaType(name = "unsignedByte")
        protected short decimals;
        @XmlElement(required = true)
        protected BigDecimal minstep;
        @XmlSchemaType(name = "unsignedInt")
        protected long lotsize;
        @XmlElement(name = "point_cost", required = true)
        protected BigDecimal pointCost;
        @XmlAttribute(name = "seccode", required = true)
        protected String seccode;
        @XmlAttribute(name = "board", required = true)
        protected String board;

        /**
         * Gets the value of the market property.
         * 
         */
        public short getMarket() {
            return market;
        }

        /**
         * Sets the value of the market property.
         * 
         */
        public void setMarket(short value) {
            this.market = value;
        }

        /**
         * Gets the value of the decimals property.
         * 
         */
        public short getDecimals() {
            return decimals;
        }

        /**
         * Sets the value of the decimals property.
         * 
         */
        public void setDecimals(short value) {
            this.decimals = value;
        }

        /**
         * Gets the value of the minstep property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinstep() {
            return minstep;
        }

        /**
         * Sets the value of the minstep property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinstep(BigDecimal value) {
            this.minstep = value;
        }

        /**
         * Gets the value of the lotsize property.
         * 
         */
        public long getLotsize() {
            return lotsize;
        }

        /**
         * Sets the value of the lotsize property.
         * 
         */
        public void setLotsize(long value) {
            this.lotsize = value;
        }

        /**
         * Gets the value of the pointCost property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPointCost() {
            return pointCost;
        }

        /**
         * Sets the value of the pointCost property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPointCost(BigDecimal value) {
            this.pointCost = value;
        }

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

    }

}
