//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 01:25:49 PM MSK 
//


package ru.kaserv.transaq.object;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="open_equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="chrgoff_ir" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="init_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="chrgoff_mr" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="maint_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="reg_equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="reg_ir" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="reg_mr" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="vm" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="finres" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="go" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="vm_mma" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="money" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="asset" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="setoff_rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="init_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="maint_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="balance_prc" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="unrealized_pnl" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="reg_equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="riskrate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="riskrate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="reserate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="reserate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="pl" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="maxbuy" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="maxsell" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="union" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="client" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "openEquity",
    "equity",
    "chrgoffIr",
    "initReq",
    "chrgoffMr",
    "maintReq",
    "regEquity",
    "regIr",
    "regMr",
    "vm",
    "finres",
    "go",
    "vmMma",
    "money",
    "asset"
})
@XmlRootElement(name = "united_portfolio")
public class PortfolioUnited {

    @XmlElement(name = "open_equity")
    protected float openEquity;
    protected float equity;
    @XmlElement(name = "chrgoff_ir")
    protected float chrgoffIr;
    @XmlElement(name = "init_req")
    protected float initReq;
    @XmlElement(name = "chrgoff_mr")
    protected float chrgoffMr;
    @XmlElement(name = "maint_req")
    protected float maintReq;
    @XmlElement(name = "reg_equity")
    protected float regEquity;
    @XmlElement(name = "reg_ir")
    protected float regIr;
    @XmlElement(name = "reg_mr")
    protected float regMr;
    protected float vm;
    protected float finres;
    protected float go;
    @XmlElement(name = "vm_mma")
    protected float vmMma;
    protected List<PortfolioUnited.Money> money;
    protected List<PortfolioUnited.Asset> asset;
    @XmlAttribute(name = "union")
    protected String union;
    @XmlAttribute(name = "client")
    protected String client;

    /**
     * Gets the value of the openEquity property.
     * 
     */
    public float getOpenEquity() {
        return openEquity;
    }

    /**
     * Sets the value of the openEquity property.
     * 
     */
    public void setOpenEquity(float value) {
        this.openEquity = value;
    }

    /**
     * Gets the value of the equity property.
     * 
     */
    public float getEquity() {
        return equity;
    }

    /**
     * Sets the value of the equity property.
     * 
     */
    public void setEquity(float value) {
        this.equity = value;
    }

    /**
     * Gets the value of the chrgoffIr property.
     * 
     */
    public float getChrgoffIr() {
        return chrgoffIr;
    }

    /**
     * Sets the value of the chrgoffIr property.
     * 
     */
    public void setChrgoffIr(float value) {
        this.chrgoffIr = value;
    }

    /**
     * Gets the value of the initReq property.
     * 
     */
    public float getInitReq() {
        return initReq;
    }

    /**
     * Sets the value of the initReq property.
     * 
     */
    public void setInitReq(float value) {
        this.initReq = value;
    }

    /**
     * Gets the value of the chrgoffMr property.
     * 
     */
    public float getChrgoffMr() {
        return chrgoffMr;
    }

    /**
     * Sets the value of the chrgoffMr property.
     * 
     */
    public void setChrgoffMr(float value) {
        this.chrgoffMr = value;
    }

    /**
     * Gets the value of the maintReq property.
     * 
     */
    public float getMaintReq() {
        return maintReq;
    }

    /**
     * Sets the value of the maintReq property.
     * 
     */
    public void setMaintReq(float value) {
        this.maintReq = value;
    }

    /**
     * Gets the value of the regEquity property.
     * 
     */
    public float getRegEquity() {
        return regEquity;
    }

    /**
     * Sets the value of the regEquity property.
     * 
     */
    public void setRegEquity(float value) {
        this.regEquity = value;
    }

    /**
     * Gets the value of the regIr property.
     * 
     */
    public float getRegIr() {
        return regIr;
    }

    /**
     * Sets the value of the regIr property.
     * 
     */
    public void setRegIr(float value) {
        this.regIr = value;
    }

    /**
     * Gets the value of the regMr property.
     * 
     */
    public float getRegMr() {
        return regMr;
    }

    /**
     * Sets the value of the regMr property.
     * 
     */
    public void setRegMr(float value) {
        this.regMr = value;
    }

    /**
     * Gets the value of the vm property.
     * 
     */
    public float getVm() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     */
    public void setVm(float value) {
        this.vm = value;
    }

    /**
     * Gets the value of the finres property.
     * 
     */
    public float getFinres() {
        return finres;
    }

    /**
     * Sets the value of the finres property.
     * 
     */
    public void setFinres(float value) {
        this.finres = value;
    }

    /**
     * Gets the value of the go property.
     * 
     */
    public float getGo() {
        return go;
    }

    /**
     * Sets the value of the go property.
     * 
     */
    public void setGo(float value) {
        this.go = value;
    }

    /**
     * Gets the value of the vmMma property.
     * 
     */
    public float getVmMma() {
        return vmMma;
    }

    /**
     * Sets the value of the vmMma property.
     * 
     */
    public void setVmMma(float value) {
        this.vmMma = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the money property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoney().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitedPortfolio.Money }
     * 
     * 
     */
    public List<PortfolioUnited.Money> getMoney() {
        if (money == null) {
            money = new ArrayList<PortfolioUnited.Money>();
        }
        return this.money;
    }

    /**
     * Gets the value of the asset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitedPortfolio.Asset }
     * 
     * 
     */
    public List<PortfolioUnited.Asset> getAsset() {
        if (asset == null) {
            asset = new ArrayList<PortfolioUnited.Asset>();
        }
        return this.asset;
    }

    /**
     * Gets the value of the union property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnion() {
        return union;
    }

    /**
     * Sets the value of the union property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnion(String value) {
        this.union = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClient(String value) {
        this.client = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="setoff_rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="init_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="maint_req" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="balance_prc" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="unrealized_pnl" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="reg_equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="riskrate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="riskrate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="reserate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="reserate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pl" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="maxbuy" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="maxsell" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "setoffRate",
        "initReq",
        "maintReq",
        "security"
    })
    public static class Asset {

        @XmlElement(name = "setoff_rate")
        protected float setoffRate;
        @XmlElement(name = "init_req")
        protected float initReq;
        @XmlElement(name = "maint_req")
        protected float maintReq;
        protected List<PortfolioUnited.Asset.Security> security;
        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the setoffRate property.
         * 
         */
        public float getSetoffRate() {
            return setoffRate;
        }

        /**
         * Sets the value of the setoffRate property.
         * 
         */
        public void setSetoffRate(float value) {
            this.setoffRate = value;
        }

        /**
         * Gets the value of the initReq property.
         * 
         */
        public float getInitReq() {
            return initReq;
        }

        /**
         * Sets the value of the initReq property.
         * 
         */
        public void setInitReq(float value) {
            this.initReq = value;
        }

        /**
         * Gets the value of the maintReq property.
         * 
         */
        public float getMaintReq() {
            return maintReq;
        }

        /**
         * Sets the value of the maintReq property.
         * 
         */
        public void setMaintReq(float value) {
            this.maintReq = value;
        }

        /**
         * Gets the value of the security property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the security property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UnitedPortfolio.Asset.Security }
         * 
         * 
         */
        public List<PortfolioUnited.Asset.Security> getSecurity() {
            if (security == null) {
                security = new ArrayList<PortfolioUnited.Asset.Security>();
            }
            return this.security;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="balance_prc" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="unrealized_pnl" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="reg_equity" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="riskrate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="riskrate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="reserate_long" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="reserate_short" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pl" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="maxbuy" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="maxsell" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "market",
            "seccode",
            "price",
            "openBalance",
            "bought",
            "sold",
            "balance",
            "balancePrc",
            "unrealizedPnl",
            "buying",
            "selling",
            "equity",
            "regEquity",
            "riskrateLong",
            "riskrateShort",
            "reserateLong",
            "reserateShort",
            "pl",
            "pnlIncome",
            "pnlIntraday",
            "maxbuy",
            "maxsell",
            "valuePart"
        })
        public static class Security {

            protected byte market;
            @XmlElement(required = true)
            protected String seccode;
            protected float price;
            @XmlElement(name = "open_balance")
            protected byte openBalance;
            protected byte bought;
            protected byte sold;
            protected byte balance;
            @XmlElement(name = "balance_prc")
            protected float balancePrc;
            @XmlElement(name = "unrealized_pnl")
            protected float unrealizedPnl;
            protected byte buying;
            protected byte selling;
            protected float equity;
            @XmlElement(name = "reg_equity")
            protected float regEquity;
            @XmlElement(name = "riskrate_long")
            protected float riskrateLong;
            @XmlElement(name = "riskrate_short")
            protected float riskrateShort;
            @XmlElement(name = "reserate_long")
            protected float reserateLong;
            @XmlElement(name = "reserate_short")
            protected float reserateShort;
            protected float pl;
            @XmlElement(name = "pnl_income")
            protected float pnlIncome;
            @XmlElement(name = "pnl_intraday")
            protected float pnlIntraday;
            protected byte maxbuy;
            protected byte maxsell;
            @XmlElement(name = "value_part")
            protected List<PortfolioUnited.Asset.Security.ValuePart> valuePart;
            @XmlAttribute(name = "secid")
            protected Byte secid;

            /**
             * Gets the value of the market property.
             * 
             */
            public byte getMarket() {
                return market;
            }

            /**
             * Sets the value of the market property.
             * 
             */
            public void setMarket(byte value) {
                this.market = value;
            }

            /**
             * Gets the value of the seccode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeccode() {
                return seccode;
            }

            /**
             * Sets the value of the seccode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeccode(String value) {
                this.seccode = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public float getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPrice(float value) {
                this.price = value;
            }

            /**
             * Gets the value of the openBalance property.
             * 
             */
            public byte getOpenBalance() {
                return openBalance;
            }

            /**
             * Sets the value of the openBalance property.
             * 
             */
            public void setOpenBalance(byte value) {
                this.openBalance = value;
            }

            /**
             * Gets the value of the bought property.
             * 
             */
            public byte getBought() {
                return bought;
            }

            /**
             * Sets the value of the bought property.
             * 
             */
            public void setBought(byte value) {
                this.bought = value;
            }

            /**
             * Gets the value of the sold property.
             * 
             */
            public byte getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             * 
             */
            public void setSold(byte value) {
                this.sold = value;
            }

            /**
             * Gets the value of the balance property.
             * 
             */
            public byte getBalance() {
                return balance;
            }

            /**
             * Sets the value of the balance property.
             * 
             */
            public void setBalance(byte value) {
                this.balance = value;
            }

            /**
             * Gets the value of the balancePrc property.
             * 
             */
            public float getBalancePrc() {
                return balancePrc;
            }

            /**
             * Sets the value of the balancePrc property.
             * 
             */
            public void setBalancePrc(float value) {
                this.balancePrc = value;
            }

            /**
             * Gets the value of the unrealizedPnl property.
             * 
             */
            public float getUnrealizedPnl() {
                return unrealizedPnl;
            }

            /**
             * Sets the value of the unrealizedPnl property.
             * 
             */
            public void setUnrealizedPnl(float value) {
                this.unrealizedPnl = value;
            }

            /**
             * Gets the value of the buying property.
             * 
             */
            public byte getBuying() {
                return buying;
            }

            /**
             * Sets the value of the buying property.
             * 
             */
            public void setBuying(byte value) {
                this.buying = value;
            }

            /**
             * Gets the value of the selling property.
             * 
             */
            public byte getSelling() {
                return selling;
            }

            /**
             * Sets the value of the selling property.
             * 
             */
            public void setSelling(byte value) {
                this.selling = value;
            }

            /**
             * Gets the value of the equity property.
             * 
             */
            public float getEquity() {
                return equity;
            }

            /**
             * Sets the value of the equity property.
             * 
             */
            public void setEquity(float value) {
                this.equity = value;
            }

            /**
             * Gets the value of the regEquity property.
             * 
             * @return 
             */
            public float getRegEquity() {
                return regEquity;
            }

            /**
             * Sets the value of the regEquity property.
             * 
             */
            public void setRegEquity(float value) {
                this.regEquity = value;
            }

            /**
             * Gets the value of the riskrateLong property.
             * 
             */
            public float getRiskrateLong() {
                return riskrateLong;
            }

            /**
             * Sets the value of the riskrateLong property.
             * 
             */
            public void setRiskrateLong(float value) {
                this.riskrateLong = value;
            }

            /**
             * Gets the value of the riskrateShort property.
             * 
             */
            public float getRiskrateShort() {
                return riskrateShort;
            }

            /**
             * Sets the value of the riskrateShort property.
             * 
             */
            public void setRiskrateShort(float value) {
                this.riskrateShort = value;
            }

            /**
             * Gets the value of the reserateLong property.
             * 
             */
            public float getReserateLong() {
                return reserateLong;
            }

            /**
             * Sets the value of the reserateLong property.
             * 
             */
            public void setReserateLong(float value) {
                this.reserateLong = value;
            }

            /**
             * Gets the value of the reserateShort property.
             * 
             */
            public float getReserateShort() {
                return reserateShort;
            }

            /**
             * Sets the value of the reserateShort property.
             * 
             */
            public void setReserateShort(float value) {
                this.reserateShort = value;
            }

            /**
             * Gets the value of the pl property.
             * 
             */
            public float getPl() {
                return pl;
            }

            /**
             * Sets the value of the pl property.
             * 
             */
            public void setPl(float value) {
                this.pl = value;
            }

            /**
             * Gets the value of the pnlIncome property.
             * 
             */
            public float getPnlIncome() {
                return pnlIncome;
            }

            /**
             * Sets the value of the pnlIncome property.
             * 
             */
            public void setPnlIncome(float value) {
                this.pnlIncome = value;
            }

            /**
             * Gets the value of the pnlIntraday property.
             * 
             */
            public float getPnlIntraday() {
                return pnlIntraday;
            }

            /**
             * Sets the value of the pnlIntraday property.
             * 
             */
            public void setPnlIntraday(float value) {
                this.pnlIntraday = value;
            }

            /**
             * Gets the value of the maxbuy property.
             * 
             */
            public byte getMaxbuy() {
                return maxbuy;
            }

            /**
             * Sets the value of the maxbuy property.
             * 
             */
            public void setMaxbuy(byte value) {
                this.maxbuy = value;
            }

            /**
             * Gets the value of the maxsell property.
             * 
             */
            public byte getMaxsell() {
                return maxsell;
            }

            /**
             * Sets the value of the maxsell property.
             * 
             */
            public void setMaxsell(byte value) {
                this.maxsell = value;
            }

            /**
             * Gets the value of the valuePart property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the valuePart property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValuePart().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link UnitedPortfolio.Asset.Security.ValuePart }
             * 
             * 
             */
            public List<PortfolioUnited.Asset.Security.ValuePart> getValuePart() {
                if (valuePart == null) {
                    valuePart = new ArrayList<PortfolioUnited.Asset.Security.ValuePart>();
                }
                return this.valuePart;
            }

            /**
             * Gets the value of the secid property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSecid() {
                return secid;
            }

            /**
             * Sets the value of the secid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSecid(Byte value) {
                this.secid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *       &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "openBalance",
                "bought",
                "sold",
                "settled",
                "balance",
                "buying",
                "selling"
            })
            public static class ValuePart {

                @XmlElement(name = "open_balance")
                protected byte openBalance;
                protected byte bought;
                protected byte sold;
                protected byte settled;
                protected byte balance;
                protected byte buying;
                protected byte selling;
                @XmlAttribute(name = "register")
                protected String register;

                /**
                 * Gets the value of the openBalance property.
                 * 
                 */
                public byte getOpenBalance() {
                    return openBalance;
                }

                /**
                 * Sets the value of the openBalance property.
                 * 
                 */
                public void setOpenBalance(byte value) {
                    this.openBalance = value;
                }

                /**
                 * Gets the value of the bought property.
                 * 
                 */
                public byte getBought() {
                    return bought;
                }

                /**
                 * Sets the value of the bought property.
                 * 
                 */
                public void setBought(byte value) {
                    this.bought = value;
                }

                /**
                 * Gets the value of the sold property.
                 * 
                 */
                public byte getSold() {
                    return sold;
                }

                /**
                 * Sets the value of the sold property.
                 * 
                 */
                public void setSold(byte value) {
                    this.sold = value;
                }

                /**
                 * Gets the value of the settled property.
                 * 
                 */
                public byte getSettled() {
                    return settled;
                }

                /**
                 * Sets the value of the settled property.
                 * 
                 */
                public void setSettled(byte value) {
                    this.settled = value;
                }

                /**
                 * Gets the value of the balance property.
                 * 
                 */
                public byte getBalance() {
                    return balance;
                }

                /**
                 * Sets the value of the balance property.
                 * 
                 */
                public void setBalance(byte value) {
                    this.balance = value;
                }

                /**
                 * Gets the value of the buying property.
                 * 
                 */
                public byte getBuying() {
                    return buying;
                }

                /**
                 * Sets the value of the buying property.
                 * 
                 */
                public void setBuying(byte value) {
                    this.buying = value;
                }

                /**
                 * Gets the value of the selling property.
                 * 
                 */
                public byte getSelling() {
                    return selling;
                }

                /**
                 * Sets the value of the selling property.
                 * 
                 */
                public void setSelling(byte value) {
                    this.selling = value;
                }

                /**
                 * Gets the value of the register property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRegister() {
                    return register;
                }

                /**
                 * Sets the value of the register property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRegister(String value) {
                    this.register = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "openBalance",
        "bought",
        "sold",
        "settled",
        "balance",
        "tax",
        "valuePart"
    })
    public static class Money {

        @XmlElement(name = "open_balance")
        protected float openBalance;
        protected float bought;
        protected float sold;
        protected float settled;
        protected float balance;
        protected float tax;
        @XmlElement(name = "value_part")
        protected List<PortfolioUnited.Money.ValuePart> valuePart;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the openBalance property.
         * 
         */
        public float getOpenBalance() {
            return openBalance;
        }

        /**
         * Sets the value of the openBalance property.
         * 
         */
        public void setOpenBalance(float value) {
            this.openBalance = value;
        }

        /**
         * Gets the value of the bought property.
         * 
         */
        public float getBought() {
            return bought;
        }

        /**
         * Sets the value of the bought property.
         * 
         */
        public void setBought(float value) {
            this.bought = value;
        }

        /**
         * Gets the value of the sold property.
         * 
         */
        public float getSold() {
            return sold;
        }

        /**
         * Sets the value of the sold property.
         * 
         */
        public void setSold(float value) {
            this.sold = value;
        }

        /**
         * Gets the value of the settled property.
         * 
         */
        public float getSettled() {
            return settled;
        }

        /**
         * Sets the value of the settled property.
         * 
         */
        public void setSettled(float value) {
            this.settled = value;
        }

        /**
         * Gets the value of the balance property.
         * 
         */
        public float getBalance() {
            return balance;
        }

        /**
         * Sets the value of the balance property.
         * 
         */
        public void setBalance(float value) {
            this.balance = value;
        }

        /**
         * Gets the value of the tax property.
         * 
         */
        public float getTax() {
            return tax;
        }

        /**
         * Sets the value of the tax property.
         * 
         */
        public void setTax(float value) {
            this.tax = value;
        }

        /**
         * Gets the value of the valuePart property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valuePart property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValuePart().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UnitedPortfolio.Money.ValuePart }
         * 
         * 
         */
        public List<PortfolioUnited.Money.ValuePart> getValuePart() {
            if (valuePart == null) {
                valuePart = new ArrayList<PortfolioUnited.Money.ValuePart>();
            }
            return this.valuePart;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *       &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "openBalance",
            "bought",
            "sold",
            "settled",
            "balance"
        })
        public static class ValuePart {

            @XmlElement(name = "open_balance")
            protected float openBalance;
            protected float bought;
            protected float sold;
            protected float settled;
            protected float balance;
            @XmlAttribute(name = "register")
            protected String register;

            /**
             * Gets the value of the openBalance property.
             * 
             */
            public float getOpenBalance() {
                return openBalance;
            }

            /**
             * Sets the value of the openBalance property.
             * 
             */
            public void setOpenBalance(float value) {
                this.openBalance = value;
            }

            /**
             * Gets the value of the bought property.
             * 
             */
            public float getBought() {
                return bought;
            }

            /**
             * Sets the value of the bought property.
             * 
             */
            public void setBought(float value) {
                this.bought = value;
            }

            /**
             * Gets the value of the sold property.
             * 
             */
            public float getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             * 
             */
            public void setSold(float value) {
                this.sold = value;
            }

            /**
             * Gets the value of the settled property.
             * 
             */
            public float getSettled() {
                return settled;
            }

            /**
             * Sets the value of the settled property.
             * 
             */
            public void setSettled(float value) {
                this.settled = value;
            }

            /**
             * Gets the value of the balance property.
             * 
             */
            public float getBalance() {
                return balance;
            }

            /**
             * Sets the value of the balance property.
             * 
             */
            public void setBalance(float value) {
                this.balance = value;
            }

            /**
             * Gets the value of the register property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegister() {
                return register;
            }

            /**
             * Sets the value of the register property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegister(String value) {
                this.register = value;
            }

        }

    }

}
