//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.20 at 12:23:44 PM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coverage_fact" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="coverage_plan" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="coverage_crit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="open_equity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="equity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cover" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="init_margin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="leverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="margin_level" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="money">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="balance_prc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="unrealized_pnl" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="cover" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="init_margin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="riskrate_long" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="riskrate_short" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="maxbuy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="maxsell" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="client" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coverageFact",
    "coveragePlan",
    "coverageCrit",
    "openEquity",
    "equity",
    "cover",
    "initMargin",
    "pnlIncome",
    "pnlIntraday",
    "leverage",
    "marginLevel",
    "money",
    "security"
})
@XmlRootElement(name = "portfolio_tplus")
public class PortfolioTplus {

    @XmlElement(name = "coverage_fact")
    protected BigDecimal coverageFact = BigDecimal.ZERO;
    @XmlElement(name = "coverage_plan")
    protected BigDecimal coveragePlan = BigDecimal.ZERO;
    @XmlElement(name = "coverage_crit")
    protected BigDecimal coverageCrit = BigDecimal.ZERO;
    @XmlElement(name = "open_equity")
    protected BigDecimal openEquity = BigDecimal.ZERO;
    @XmlElement()
    protected BigDecimal equity = BigDecimal.ZERO;
    @XmlElement()
    protected BigDecimal cover = BigDecimal.ZERO;
    @XmlElement(name = "init_margin")
    protected BigDecimal initMargin = BigDecimal.ZERO;
    @XmlElement(name = "pnl_income")
    protected BigDecimal pnlIncome = BigDecimal.ZERO;
    @XmlElement(name = "pnl_intraday")
    protected BigDecimal pnlIntraday = BigDecimal.ZERO;
    @XmlElement()
    protected BigDecimal leverage = BigDecimal.ZERO;
    @XmlElement(name = "margin_level")
    protected BigDecimal marginLevel = BigDecimal.ZERO;
    @XmlElement()
    protected PortfolioTplus.Money money;
    protected List<PortfolioTplus.Security> security;
    @XmlAttribute(name = "client")
    protected String client;

    /**
     * Gets the value of the coverageFact property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoverageFact() {
        return coverageFact;
    }

    /**
     * Sets the value of the coverageFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoverageFact(BigDecimal value) {
        this.coverageFact = value;
    }

    /**
     * Gets the value of the coveragePlan property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoveragePlan() {
        return coveragePlan;
    }

    /**
     * Sets the value of the coveragePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoveragePlan(BigDecimal value) {
        this.coveragePlan = value;
    }

    /**
     * Gets the value of the coverageCrit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoverageCrit() {
        return coverageCrit;
    }

    /**
     * Sets the value of the coverageCrit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoverageCrit(BigDecimal value) {
        this.coverageCrit = value;
    }

    /**
     * Gets the value of the openEquity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpenEquity() {
        return openEquity;
    }

    /**
     * Sets the value of the openEquity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpenEquity(BigDecimal value) {
        this.openEquity = value;
    }

    /**
     * Gets the value of the equity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEquity() {
        return equity;
    }

    /**
     * Sets the value of the equity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEquity(BigDecimal value) {
        this.equity = value;
    }

    /**
     * Gets the value of the cover property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCover() {
        return cover;
    }

    /**
     * Sets the value of the cover property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCover(BigDecimal value) {
        this.cover = value;
    }

    /**
     * Gets the value of the initMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitMargin() {
        return initMargin;
    }

    /**
     * Sets the value of the initMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitMargin(BigDecimal value) {
        this.initMargin = value;
    }

    /**
     * Gets the value of the pnlIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPnlIncome() {
        return pnlIncome;
    }

    /**
     * Sets the value of the pnlIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPnlIncome(BigDecimal value) {
        this.pnlIncome = value;
    }

    /**
     * Gets the value of the pnlIntraday property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPnlIntraday() {
        return pnlIntraday;
    }

    /**
     * Sets the value of the pnlIntraday property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPnlIntraday(BigDecimal value) {
        this.pnlIntraday = value;
    }

    /**
     * Gets the value of the leverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLeverage() {
        return leverage;
    }

    /**
     * Sets the value of the leverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLeverage(BigDecimal value) {
        this.leverage = value;
    }

    /**
     * Gets the value of the marginLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMarginLevel() {
        return marginLevel;
    }

    /**
     * Sets the value of the marginLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMarginLevel(BigDecimal value) {
        this.marginLevel = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioTplus.Money }
     *     
     */
    public PortfolioTplus.Money getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioTplus.Money }
     *     
     */
    public void setMoney(PortfolioTplus.Money value) {
        this.money = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the security property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortfolioTplus.Security }
     * 
     * 
     */
    public List<PortfolioTplus.Security> getSecurity() {
        if (security == null) {
            security = new ArrayList<PortfolioTplus.Security>();
        }
        return this.security;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClient(String value) {
        this.client = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "openBalance",
        "bought",
        "sold",
        "settled",
        "balance",
        "tax",
        "valuePart"
    })
    public static class Money {

        @XmlElement(name = "open_balance")
        protected BigDecimal openBalance;
        @XmlElement()
        protected BigDecimal bought;
        @XmlElement()
        protected BigDecimal sold;
        @XmlElement()
        protected BigDecimal settled;
        @XmlElement()
        protected BigDecimal balance;
        @XmlElement()
        protected BigDecimal tax;
        @XmlElement(name = "value_part")
        protected List<PortfolioTplus.Money.ValuePart> valuePart;

        /**
         * Gets the value of the openBalance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOpenBalance() {
            return openBalance;
        }

        /**
         * Sets the value of the openBalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOpenBalance(BigDecimal value) {
            this.openBalance = value;
        }

        /**
         * Gets the value of the bought property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBought() {
            return bought;
        }

        /**
         * Sets the value of the bought property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBought(BigDecimal value) {
            this.bought = value;
        }

        /**
         * Gets the value of the sold property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSold() {
            return sold;
        }

        /**
         * Sets the value of the sold property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSold(BigDecimal value) {
            this.sold = value;
        }

        /**
         * Gets the value of the settled property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSettled() {
            return settled;
        }

        /**
         * Sets the value of the settled property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSettled(BigDecimal value) {
            this.settled = value;
        }

        /**
         * Gets the value of the balance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBalance() {
            return balance;
        }

        /**
         * Sets the value of the balance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBalance(BigDecimal value) {
            this.balance = value;
        }

        /**
         * Gets the value of the tax property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTax() {
            return tax;
        }

        /**
         * Sets the value of the tax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTax(BigDecimal value) {
            this.tax = value;
        }

        /**
         * Gets the value of the valuePart property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valuePart property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValuePart().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PortfolioTplus.Money.ValuePart }
         * 
         * 
         */
        public List<PortfolioTplus.Money.ValuePart> getValuePart() {
            if (valuePart == null) {
                valuePart = new ArrayList<PortfolioTplus.Money.ValuePart>();
            }
            return this.valuePart;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *       &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "openBalance",
            "bought",
            "sold",
            "settled",
            "balance"
        })
        public static class ValuePart {

            @XmlElement(name = "open_balance")
            protected BigDecimal openBalance;
            @XmlElement()
            protected BigDecimal bought;
            @XmlElement()
            protected BigDecimal sold;
            @XmlElement()
            protected BigDecimal settled;
            @XmlElement()
            protected BigDecimal balance;
            @XmlAttribute(name = "register")
            protected String register;

            /**
             * Gets the value of the openBalance property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getOpenBalance() {
                return openBalance;
            }

            /**
             * Sets the value of the openBalance property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setOpenBalance(BigDecimal value) {
                this.openBalance = value;
            }

            /**
             * Gets the value of the bought property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBought() {
                return bought;
            }

            /**
             * Sets the value of the bought property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBought(BigDecimal value) {
                this.bought = value;
            }

            /**
             * Gets the value of the sold property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSold(BigDecimal value) {
                this.sold = value;
            }

            /**
             * Gets the value of the settled property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSettled() {
                return settled;
            }

            /**
             * Sets the value of the settled property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSettled(BigDecimal value) {
                this.settled = value;
            }

            /**
             * Gets the value of the balance property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getBalance() {
                return balance;
            }

            /**
             * Sets the value of the balance property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setBalance(BigDecimal value) {
                this.balance = value;
            }

            /**
             * Gets the value of the register property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegister() {
                return register;
            }

            /**
             * Sets the value of the register property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegister(String value) {
                this.register = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="balance_prc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="unrealized_pnl" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="cover" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="init_margin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="riskrate_long" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="riskrate_short" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="pnl_income" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="pnl_intraday" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="maxbuy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="maxsell" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="value_part" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "market",
        "seccode",
        "price",
        "openBalance",
        "bought",
        "sold",
        "balance",
        "balancePrc",
        "unrealizedPnl",
        "buying",
        "selling",
        "cover",
        "initMargin",
        "riskrateLong",
        "riskrateShort",
        "pnlIncome",
        "pnlIntraday",
        "maxbuy",
        "maxsell",
        "valuePart"
    })
    public static class Security {

        protected int market;
        @XmlElement()
        protected String seccode;
        @XmlElement()
        protected BigDecimal price;
        @XmlElement(name = "open_balance")
        protected int openBalance;
        protected int bought;
        protected int sold;
        protected int balance;
        @XmlElement(name = "balance_prc")
        protected BigDecimal balancePrc;
        @XmlElement(name = "unrealized_pnl")
        protected BigDecimal unrealizedPnl;
        protected int buying;
        protected int selling;
        @XmlElement(required = true)
        protected BigDecimal cover;
        @XmlElement(name = "init_margin")
        protected BigDecimal initMargin;
        @XmlElement(name = "riskrate_long")
        protected BigDecimal riskrateLong;
        @XmlElement(name = "riskrate_short")
        protected BigDecimal riskrateShort;
        @XmlElement(name = "pnl_income")
        protected BigDecimal pnlIncome;
        @XmlElement(name = "pnl_intraday")
        protected BigDecimal pnlIntraday;
        protected int maxbuy;
        protected int maxsell;
        @XmlElement(name = "value_part")
        protected List<PortfolioTplus.Security.ValuePart> valuePart;
        @XmlAttribute(name = "secid")
        protected Integer secid;

        /**
         * Gets the value of the market property.
         * 
         */
        public int getMarket() {
            return market;
        }

        /**
         * Sets the value of the market property.
         * 
         */
        public void setMarket(int value) {
            this.market = value;
        }

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the openBalance property.
         * 
         */
        public int getOpenBalance() {
            return openBalance;
        }

        /**
         * Sets the value of the openBalance property.
         * 
         */
        public void setOpenBalance(int value) {
            this.openBalance = value;
        }

        /**
         * Gets the value of the bought property.
         * 
         */
        public int getBought() {
            return bought;
        }

        /**
         * Sets the value of the bought property.
         * 
         */
        public void setBought(int value) {
            this.bought = value;
        }

        /**
         * Gets the value of the sold property.
         * 
         */
        public int getSold() {
            return sold;
        }

        /**
         * Sets the value of the sold property.
         * 
         */
        public void setSold(int value) {
            this.sold = value;
        }

        /**
         * Gets the value of the balance property.
         * 
         */
        public int getBalance() {
            return balance;
        }

        /**
         * Sets the value of the balance property.
         * 
         */
        public void setBalance(int value) {
            this.balance = value;
        }

        /**
         * Gets the value of the balancePrc property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBalancePrc() {
            return balancePrc;
        }

        /**
         * Sets the value of the balancePrc property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBalancePrc(BigDecimal value) {
            this.balancePrc = value;
        }

        /**
         * Gets the value of the unrealizedPnl property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUnrealizedPnl() {
            return unrealizedPnl;
        }

        /**
         * Sets the value of the unrealizedPnl property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUnrealizedPnl(BigDecimal value) {
            this.unrealizedPnl = value;
        }

        /**
         * Gets the value of the buying property.
         * 
         */
        public int getBuying() {
            return buying;
        }

        /**
         * Sets the value of the buying property.
         * 
         */
        public void setBuying(int value) {
            this.buying = value;
        }

        /**
         * Gets the value of the selling property.
         * 
         */
        public int getSelling() {
            return selling;
        }

        /**
         * Sets the value of the selling property.
         * 
         */
        public void setSelling(int value) {
            this.selling = value;
        }

        /**
         * Gets the value of the cover property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCover() {
            return cover;
        }

        /**
         * Sets the value of the cover property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCover(BigDecimal value) {
            this.cover = value;
        }

        /**
         * Gets the value of the initMargin property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInitMargin() {
            return initMargin;
        }

        /**
         * Sets the value of the initMargin property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInitMargin(BigDecimal value) {
            this.initMargin = value;
        }

        /**
         * Gets the value of the riskrateLong property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRiskrateLong() {
            return riskrateLong;
        }

        /**
         * Sets the value of the riskrateLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRiskrateLong(BigDecimal value) {
            this.riskrateLong = value;
        }

        /**
         * Gets the value of the riskrateShort property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRiskrateShort() {
            return riskrateShort;
        }

        /**
         * Sets the value of the riskrateShort property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRiskrateShort(BigDecimal value) {
            this.riskrateShort = value;
        }

        /**
         * Gets the value of the pnlIncome property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPnlIncome() {
            return pnlIncome;
        }

        /**
         * Sets the value of the pnlIncome property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPnlIncome(BigDecimal value) {
            this.pnlIncome = value;
        }

        /**
         * Gets the value of the pnlIntraday property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPnlIntraday() {
            return pnlIntraday;
        }

        /**
         * Sets the value of the pnlIntraday property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPnlIntraday(BigDecimal value) {
            this.pnlIntraday = value;
        }

        /**
         * Gets the value of the maxbuy property.
         * 
         */
        public int getMaxbuy() {
            return maxbuy;
        }

        /**
         * Sets the value of the maxbuy property.
         * 
         */
        public void setMaxbuy(int value) {
            this.maxbuy = value;
        }

        /**
         * Gets the value of the maxsell property.
         * 
         */
        public int getMaxsell() {
            return maxsell;
        }

        /**
         * Sets the value of the maxsell property.
         * 
         */
        public void setMaxsell(int value) {
            this.maxsell = value;
        }

        /**
         * Gets the value of the valuePart property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valuePart property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValuePart().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PortfolioTplus.Security.ValuePart }
         * 
         * 
         */
        public List<PortfolioTplus.Security.ValuePart> getValuePart() {
            if (valuePart == null) {
                valuePart = new ArrayList<PortfolioTplus.Security.ValuePart>();
            }
            return this.valuePart;
        }

        /**
         * Gets the value of the secid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSecid(Integer value) {
            this.secid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="open_balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="bought" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="sold" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="settled" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="buying" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="selling" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *       &lt;attribute name="register" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "openBalance",
            "bought",
            "sold",
            "settled",
            "balance",
            "buying",
            "selling"
        })
        public static class ValuePart {

            @XmlElement(name = "open_balance")
            protected int openBalance;
            protected int bought;
            protected int sold;
            protected int settled;
            protected int balance;
            protected int buying;
            protected int selling;
            @XmlAttribute(name = "register")
            protected String register;

            /**
             * Gets the value of the openBalance property.
             * 
             */
            public int getOpenBalance() {
                return openBalance;
            }

            /**
             * Sets the value of the openBalance property.
             * 
             */
            public void setOpenBalance(int value) {
                this.openBalance = value;
            }

            /**
             * Gets the value of the bought property.
             * 
             */
            public int getBought() {
                return bought;
            }

            /**
             * Sets the value of the bought property.
             * 
             */
            public void setBought(int value) {
                this.bought = value;
            }

            /**
             * Gets the value of the sold property.
             * 
             */
            public int getSold() {
                return sold;
            }

            /**
             * Sets the value of the sold property.
             * 
             */
            public void setSold(int value) {
                this.sold = value;
            }

            /**
             * Gets the value of the settled property.
             * 
             */
            public int getSettled() {
                return settled;
            }

            /**
             * Sets the value of the settled property.
             * 
             */
            public void setSettled(int value) {
                this.settled = value;
            }

            /**
             * Gets the value of the balance property.
             * 
             */
            public int getBalance() {
                return balance;
            }

            /**
             * Sets the value of the balance property.
             * 
             */
            public void setBalance(int value) {
                this.balance = value;
            }

            /**
             * Gets the value of the buying property.
             * 
             */
            public int getBuying() {
                return buying;
            }

            /**
             * Sets the value of the buying property.
             * 
             */
            public void setBuying(int value) {
                this.buying = value;
            }

            /**
             * Gets the value of the selling property.
             * 
             */
            public int getSelling() {
                return selling;
            }

            /**
             * Sets the value of the selling property.
             * 
             */
            public void setSelling(int value) {
                this.selling = value;
            }

            /**
             * Gets the value of the register property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegister() {
                return register;
            }

            /**
             * Sets the value of the register property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegister(String value) {
                this.register = value;
            }

        }

    }
 
    
    

}
