//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.23 at 12:03:18 PM MSK 
//


package ru.kaserv.transaq.object;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import static java.math.BigDecimal.ZERO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quote" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="sell" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                   &lt;element name="buy" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="secid" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quote"
})
@XmlRootElement(name = "quotes")
public class Quotes {

    @XmlElement(required = true)
    protected List<Quotes.Quote> quote;

    /**
     * Gets the value of the quote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quotes.Quote }
     * 
     * 
     */
    public List<Quotes.Quote> getQuote() {
        if (quote == null) {
            quote = new ArrayList<Quotes.Quote>();
        }
        return this.quote;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="sell" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *         &lt;element name="buy" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="secid" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "board",
        "seccode",
        "price",
        "yield",
        "sell",
        "buy"
    })
    
    public static class Quote implements Comparable{

        @Override
        public int compareTo(Object o) {
            int result=0;
            Quote other = (Quote) o;    
            result = this.price.compareTo(other.price);
            return result;
        }

        @XmlElement(required = true)
        protected String board;
        @XmlElement(required = true)
        protected String seccode;
        @XmlElement(required = true)
        protected BigDecimal price;
        @XmlSchemaType(name = "unsignedByte")
        protected short yield;
        @XmlSchemaType(name = "unsignedShort")
        protected Integer sell;
        @XmlSchemaType(name = "unsignedShort")
        protected Integer buy;
        @XmlAttribute(name = "secid", required = true)
        @XmlSchemaType(name = "unsignedShort")
        protected int secid;

        public Quote() {
            this.board = "";
            this.seccode = "";
            this.price = ZERO;
            this.yield = 0;
            this.sell = 0;
            this.buy = 0;
            this.secid = 0;
        }

        
        
        
        
  

        @Override
        public boolean equals(Object object) {
            // TODO: Warning - this method won't work in the case the id fields are not set
            if (!(object instanceof Quote)) {
                return false;
            }
            Quote other = (Quote) object;
            if (this.price == null || other.price == null) {
                return false;
            }
            
            if (!this.board.equals(other.board)) {
                return false;
            }
            
            if (!this.seccode.equals(other.seccode)) {
                return false;
            }
            
            //сравним цены
            //int     compareTo(BigDecimal val) — сравнение. Возвращает 1, если текущее значение больше val, 0 если текущее значение равно val, -1 если текущее значение меньше val.  
           if ( this.price.compareTo(other.price) == 0){            
                return true;  
           }
           else{
               return false;
           }
               
            
        }

 
        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the yield property.
         * 
         */
        public short getYield() {
            return yield;
        }

        /**
         * Sets the value of the yield property.
         * 
         */
        public void setYield(short value) {
            this.yield = value;
        }

        /**
         * Gets the value of the sell property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSell() {
            return sell;
        }

        /**
         * Sets the value of the sell property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSell(Integer value) {
            this.sell = value;
        }

        /**
         * Gets the value of the buy property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBuy() {
            return buy;
        }

        /**
         * Sets the value of the buy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBuy(Integer value) {
            this.buy = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         */
        public int getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         */
        public void setSecid(int value) {
            this.secid = value;
        }

    }

}
