//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.27 at 11:32:30 AM MSK 
//


package ru.kaserv.transaq.object;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instrclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decimals" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="minstep" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="lotsize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="point_cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="opmask">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bymarket" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nosplit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fok" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ioc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sectype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sec_tz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="quotestype" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "security"
})
@XmlRootElement(name = "securities")
public class Securities {

    protected List<Securities.Security> security;

    /**
     * Gets the value of the security property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the security property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Securities.Security }
     * 
     * 
     */
    public List<Securities.Security> getSecurity() {
        if (security == null) {
            security = new ArrayList<Securities.Security>();
        }
        return this.security;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instrclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="market" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decimals" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="minstep" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="lotsize" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="point_cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="opmask">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bymarket" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="nosplit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fok" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ioc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sectype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sec_tz" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="quotestype" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *       &lt;attribute name="secid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seccode",
        "instrclass",
        "board",
        "market",
        "shortname",
        "decimals",
        "minstep",
        "lotsize",
        "pointCost",
        "opmask",
        "sectype",
        "secTz",
        "quotestype"
    })
    public static class Security {

        @XmlElement(required = true)
        protected String seccode;
        @XmlElement(required = true)
        protected String instrclass;
        @XmlElement(required = true)
        protected String board;
        @XmlElement(required = true)
        protected String market;
        @XmlElement(required = true)
        protected String shortname;
        protected int decimals;
        @XmlElement(required = true)
        protected BigDecimal minstep;
        protected int lotsize;
        @XmlElement(name = "point_cost", required = true)
        protected BigDecimal pointCost;
        @XmlElement(required = true)
        protected Securities.Security.Opmask opmask;
        @XmlElement(required = true)
        protected String sectype;
        @XmlElement(name = "sec_tz", required = true)
        protected String secTz;
        protected int quotestype;
        @XmlAttribute(name = "secid")
        protected Integer secid;
        @XmlAttribute(name = "active")
        protected String active;

        /**
         * Gets the value of the seccode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccode() {
            return seccode;
        }

        /**
         * Sets the value of the seccode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccode(String value) {
            this.seccode = value;
        }

        /**
         * Gets the value of the instrclass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstrclass() {
            return instrclass;
        }

        /**
         * Sets the value of the instrclass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstrclass(String value) {
            this.instrclass = value;
        }

        /**
         * Gets the value of the board property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBoard() {
            return board;
        }

        /**
         * Sets the value of the board property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBoard(String value) {
            this.board = value;
        }

        /**
         * Gets the value of the market property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarket() {
            return market;
        }

        /**
         * Sets the value of the market property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarket(String value) {
            this.market = value;
        }

        /**
         * Gets the value of the shortname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortname() {
            return shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortname(String value) {
            this.shortname = value;
        }

        /**
         * Gets the value of the decimals property.
         * 
         */
        public int getDecimals() {
            return decimals;
        }

        /**
         * Sets the value of the decimals property.
         * 
         */
        public void setDecimals(int value) {
            this.decimals = value;
        }

        /**
         * Gets the value of the minstep property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinstep() {
            return minstep;
        }

        /**
         * Sets the value of the minstep property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinstep(BigDecimal value) {
            this.minstep = value;
        }

        /**
         * Gets the value of the lotsize property.
         * 
         */
        public int getLotsize() {
            return lotsize;
        }

        /**
         * Sets the value of the lotsize property.
         * 
         */
        public void setLotsize(int value) {
            this.lotsize = value;
        }

        /**
         * Gets the value of the pointCost property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPointCost() {
            return pointCost;
        }

        /**
         * Sets the value of the pointCost property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPointCost(BigDecimal value) {
            this.pointCost = value;
        }

        /**
         * Gets the value of the opmask property.
         * 
         * @return
         *     possible object is
         *     {@link Securities.Security.Opmask }
         *     
         */
        public Securities.Security.Opmask getOpmask() {
            return opmask;
        }

        /**
         * Sets the value of the opmask property.
         * 
         * @param value
         *     allowed object is
         *     {@link Securities.Security.Opmask }
         *     
         */
        public void setOpmask(Securities.Security.Opmask value) {
            this.opmask = value;
        }

        /**
         * Gets the value of the sectype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSectype() {
            return sectype;
        }

        /**
         * Sets the value of the sectype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSectype(String value) {
            this.sectype = value;
        }

        /**
         * Gets the value of the secTz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecTz() {
            return secTz;
        }

        /**
         * Sets the value of the secTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecTz(String value) {
            this.secTz = value;
        }

        /**
         * Gets the value of the quotestype property.
         * 
         */
        public int getQuotestype() {
            return quotestype;
        }

        /**
         * Sets the value of the quotestype property.
         * 
         */
        public void setQuotestype(int value) {
            this.quotestype = value;
        }

        /**
         * Gets the value of the secid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSecid() {
            return secid;
        }

        /**
         * Sets the value of the secid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSecid(Integer value) {
            this.secid = value;
        }

        /**
         * Gets the value of the active property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActive(String value) {
            this.active = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="usecredit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bymarket" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="nosplit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fok" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ioc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Opmask {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "usecredit")
            protected String usecredit;
            @XmlAttribute(name = "bymarket")
            protected String bymarket;
            @XmlAttribute(name = "nosplit")
            protected String nosplit;
            @XmlAttribute(name = "fok")
            protected String fok;
            @XmlAttribute(name = "ioc")
            protected String ioc;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the usecredit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsecredit() {
                return usecredit;
            }

            /**
             * Sets the value of the usecredit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsecredit(String value) {
                this.usecredit = value;
            }

            /**
             * Gets the value of the bymarket property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBymarket() {
                return bymarket;
            }

            /**
             * Sets the value of the bymarket property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBymarket(String value) {
                this.bymarket = value;
            }

            /**
             * Gets the value of the nosplit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNosplit() {
                return nosplit;
            }

            /**
             * Sets the value of the nosplit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNosplit(String value) {
                this.nosplit = value;
            }

            /**
             * Gets the value of the fok property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFok() {
                return fok;
            }

            /**
             * Sets the value of the fok property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFok(String value) {
                this.fok = value;
            }

            /**
             * Gets the value of the ioc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIoc() {
                return ioc;
            }

            /**
             * Sets the value of the ioc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIoc(String value) {
                this.ioc = value;
            }

        }

    }

}
