//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.11 at 03:01:02 PM MSK 
//


package java_classes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cbplimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cbplused" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cbplplanned" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="fob_varmargin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="coverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="liquidity_c" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="profit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="money_current" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="money_reserve" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="money_free" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="options_premium" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="exchange_fee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="forts_varmargin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="varmargin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pclmargin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="options_vm" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="spot_buy_limit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="used_spot_buy_limit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="collat_current" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="collat_blocked" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="collat_free" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *       &lt;attribute name="client" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cbplimit",
    "cbplused",
    "cbplplanned",
    "fobVarmargin",
    "coverage",
    "liquidityC",
    "profit",
    "moneyCurrent",
    "moneyReserve",
    "moneyFree",
    "optionsPremium",
    "exchangeFee",
    "fortsVarmargin",
    "varmargin",
    "pclmargin",
    "optionsVm",
    "spotBuyLimit",
    "usedSpotBuyLimit",
    "collatCurrent",
    "collatBlocked",
    "collatFree"
})
@XmlRootElement(name = "clientlimits")
public class Clientlimits {

    @XmlElement(required = true)
    protected BigDecimal cbplimit;
    @XmlElement(required = true)
    protected BigDecimal cbplused;
    @XmlElement(required = true)
    protected BigDecimal cbplplanned;
    @XmlElement(name = "fob_varmargin", required = true)
    protected BigDecimal fobVarmargin;
    @XmlElement(required = true)
    protected BigDecimal coverage;
    @XmlElement(name = "liquidity_c", required = true)
    protected BigDecimal liquidityC;
    @XmlElement(required = true)
    protected BigDecimal profit;
    @XmlElement(name = "money_current", required = true)
    protected BigDecimal moneyCurrent;
    @XmlElement(name = "money_reserve", required = true)
    protected BigDecimal moneyReserve;
    @XmlElement(name = "money_free", required = true)
    protected BigDecimal moneyFree;
    @XmlElement(name = "options_premium", required = true)
    protected BigDecimal optionsPremium;
    @XmlElement(name = "exchange_fee", required = true)
    protected BigDecimal exchangeFee;
    @XmlElement(name = "forts_varmargin", required = true)
    protected BigDecimal fortsVarmargin;
    @XmlElement(required = true)
    protected BigDecimal varmargin;
    @XmlElement(required = true)
    protected BigDecimal pclmargin;
    @XmlElement(name = "options_vm", required = true)
    protected BigDecimal optionsVm;
    @XmlElement(name = "spot_buy_limit", required = true)
    protected BigDecimal spotBuyLimit;
    @XmlElement(name = "used_spot_buy_limit", required = true)
    protected BigDecimal usedSpotBuyLimit;
    @XmlElement(name = "collat_current", required = true)
    protected BigDecimal collatCurrent;
    @XmlElement(name = "collat_blocked", required = true)
    protected BigDecimal collatBlocked;
    @XmlElement(name = "collat_free", required = true)
    protected BigDecimal collatFree;
    @XmlAttribute(name = "client")
    protected String client;

    /**
     * Gets the value of the cbplimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCbplimit() {
        return cbplimit;
    }

    /**
     * Sets the value of the cbplimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCbplimit(BigDecimal value) {
        this.cbplimit = value;
    }

    /**
     * Gets the value of the cbplused property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCbplused() {
        return cbplused;
    }

    /**
     * Sets the value of the cbplused property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCbplused(BigDecimal value) {
        this.cbplused = value;
    }

    /**
     * Gets the value of the cbplplanned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCbplplanned() {
        return cbplplanned;
    }

    /**
     * Sets the value of the cbplplanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCbplplanned(BigDecimal value) {
        this.cbplplanned = value;
    }

    /**
     * Gets the value of the fobVarmargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFobVarmargin() {
        return fobVarmargin;
    }

    /**
     * Sets the value of the fobVarmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFobVarmargin(BigDecimal value) {
        this.fobVarmargin = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoverage(BigDecimal value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the liquidityC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLiquidityC() {
        return liquidityC;
    }

    /**
     * Sets the value of the liquidityC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLiquidityC(BigDecimal value) {
        this.liquidityC = value;
    }

    /**
     * Gets the value of the profit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * Sets the value of the profit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProfit(BigDecimal value) {
        this.profit = value;
    }

    /**
     * Gets the value of the moneyCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoneyCurrent() {
        return moneyCurrent;
    }

    /**
     * Sets the value of the moneyCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoneyCurrent(BigDecimal value) {
        this.moneyCurrent = value;
    }

    /**
     * Gets the value of the moneyReserve property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoneyReserve() {
        return moneyReserve;
    }

    /**
     * Sets the value of the moneyReserve property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoneyReserve(BigDecimal value) {
        this.moneyReserve = value;
    }

    /**
     * Gets the value of the moneyFree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoneyFree() {
        return moneyFree;
    }

    /**
     * Sets the value of the moneyFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoneyFree(BigDecimal value) {
        this.moneyFree = value;
    }

    /**
     * Gets the value of the optionsPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOptionsPremium() {
        return optionsPremium;
    }

    /**
     * Sets the value of the optionsPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOptionsPremium(BigDecimal value) {
        this.optionsPremium = value;
    }

    /**
     * Gets the value of the exchangeFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchangeFee() {
        return exchangeFee;
    }

    /**
     * Sets the value of the exchangeFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchangeFee(BigDecimal value) {
        this.exchangeFee = value;
    }

    /**
     * Gets the value of the fortsVarmargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFortsVarmargin() {
        return fortsVarmargin;
    }

    /**
     * Sets the value of the fortsVarmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFortsVarmargin(BigDecimal value) {
        this.fortsVarmargin = value;
    }

    /**
     * Gets the value of the varmargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVarmargin() {
        return varmargin;
    }

    /**
     * Sets the value of the varmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVarmargin(BigDecimal value) {
        this.varmargin = value;
    }

    /**
     * Gets the value of the pclmargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPclmargin() {
        return pclmargin;
    }

    /**
     * Sets the value of the pclmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPclmargin(BigDecimal value) {
        this.pclmargin = value;
    }

    /**
     * Gets the value of the optionsVm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOptionsVm() {
        return optionsVm;
    }

    /**
     * Sets the value of the optionsVm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOptionsVm(BigDecimal value) {
        this.optionsVm = value;
    }

    /**
     * Gets the value of the spotBuyLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpotBuyLimit() {
        return spotBuyLimit;
    }

    /**
     * Sets the value of the spotBuyLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpotBuyLimit(BigDecimal value) {
        this.spotBuyLimit = value;
    }

    /**
     * Gets the value of the usedSpotBuyLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUsedSpotBuyLimit() {
        return usedSpotBuyLimit;
    }

    /**
     * Sets the value of the usedSpotBuyLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUsedSpotBuyLimit(BigDecimal value) {
        this.usedSpotBuyLimit = value;
    }

    /**
     * Gets the value of the collatCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCollatCurrent() {
        return collatCurrent;
    }

    /**
     * Sets the value of the collatCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCollatCurrent(BigDecimal value) {
        this.collatCurrent = value;
    }

    /**
     * Gets the value of the collatBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCollatBlocked() {
        return collatBlocked;
    }

    /**
     * Sets the value of the collatBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCollatBlocked(BigDecimal value) {
        this.collatBlocked = value;
    }

    /**
     * Gets the value of the collatFree property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCollatFree() {
        return collatFree;
    }

    /**
     * Sets the value of the collatFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCollatFree(BigDecimal value) {
        this.collatFree = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClient(String value) {
        this.client = value;
    }

}
