//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 01:53:12 PM MSK 
//


package java_classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the java_classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: java_classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubscribeCommand }
     * 
     */
    public SubscribeCommand createSubscribeCommand() {
        return new SubscribeCommand();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Quotes }
     * 
     */
    public SubscribeCommand.Quotes createSubscribeCommandQuotes() {
        return new SubscribeCommand.Quotes();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Quotations }
     * 
     */
    public SubscribeCommand.Quotations createSubscribeCommandQuotations() {
        return new SubscribeCommand.Quotations();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Alltrades }
     * 
     */
    public SubscribeCommand.Alltrades createSubscribeCommandAlltrades() {
        return new SubscribeCommand.Alltrades();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Quotes.Security }
     * 
     */
    public SubscribeCommand.Quotes.Security createSubscribeCommandQuotesSecurity() {
        return new SubscribeCommand.Quotes.Security();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Quotations.Security }
     * 
     */
    public SubscribeCommand.Quotations.Security createSubscribeCommandQuotationsSecurity() {
        return new SubscribeCommand.Quotations.Security();
    }

    /**
     * Create an instance of {@link SubscribeCommand.Alltrades.Security }
     * 
     */
    public SubscribeCommand.Alltrades.Security createSubscribeCommandAlltradesSecurity() {
        return new SubscribeCommand.Alltrades.Security();
    }

}
