//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 01:53:12 PM MSK 
//


package java_classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alltrades">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="quotations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="quotes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alltrades",
    "quotations",
    "quotes"
})
@XmlRootElement(name = "SubscribeCommand")
public class SubscribeCommand {

    @XmlElement(required = true)
    protected SubscribeCommand.Alltrades alltrades;
    @XmlElement(required = true)
    protected SubscribeCommand.Quotations quotations;
    @XmlElement(required = true)
    protected SubscribeCommand.Quotes quotes;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the alltrades property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribeCommand.Alltrades }
     *     
     */
    public SubscribeCommand.Alltrades getAlltrades() {
        return alltrades;
    }

    /**
     * Sets the value of the alltrades property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribeCommand.Alltrades }
     *     
     */
    public void setAlltrades(SubscribeCommand.Alltrades value) {
        this.alltrades = value;
    }

    /**
     * Gets the value of the quotations property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribeCommand.Quotations }
     *     
     */
    public SubscribeCommand.Quotations getQuotations() {
        return quotations;
    }

    /**
     * Sets the value of the quotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribeCommand.Quotations }
     *     
     */
    public void setQuotations(SubscribeCommand.Quotations value) {
        this.quotations = value;
    }

    /**
     * Gets the value of the quotes property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribeCommand.Quotes }
     *     
     */
    public SubscribeCommand.Quotes getQuotes() {
        return quotes;
    }

    /**
     * Sets the value of the quotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribeCommand.Quotes }
     *     
     */
    public void setQuotes(SubscribeCommand.Quotes value) {
        this.quotes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "security"
    })
    public static class Alltrades {

        protected List<SubscribeCommand.Alltrades.Security> security;

        /**
         * Gets the value of the security property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the security property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubscribeCommand.Alltrades.Security }
         * 
         * 
         */
        public List<SubscribeCommand.Alltrades.Security> getSecurity() {
            if (security == null) {
                security = new ArrayList<SubscribeCommand.Alltrades.Security>();
            }
            return this.security;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "board",
            "seccode"
        })
        public static class Security {

            @XmlElement(required = true)
            protected String board;
            @XmlElement(required = true)
            protected String seccode;

            /**
             * Gets the value of the board property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBoard() {
                return board;
            }

            /**
             * Sets the value of the board property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoard(String value) {
                this.board = value;
            }

            /**
             * Gets the value of the seccode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeccode() {
                return seccode;
            }

            /**
             * Sets the value of the seccode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeccode(String value) {
                this.seccode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "security"
    })
    public static class Quotations {

        protected List<SubscribeCommand.Quotations.Security> security;

        /**
         * Gets the value of the security property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the security property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubscribeCommand.Quotations.Security }
         * 
         * 
         */
        public List<SubscribeCommand.Quotations.Security> getSecurity() {
            if (security == null) {
                security = new ArrayList<SubscribeCommand.Quotations.Security>();
            }
            return this.security;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "board",
            "seccode"
        })
        public static class Security {

            @XmlElement(required = true)
            protected String board;
            @XmlElement(required = true)
            protected String seccode;

            /**
             * Gets the value of the board property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBoard() {
                return board;
            }

            /**
             * Sets the value of the board property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoard(String value) {
                this.board = value;
            }

            /**
             * Gets the value of the seccode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeccode() {
                return seccode;
            }

            /**
             * Sets the value of the seccode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeccode(String value) {
                this.seccode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="security" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "security"
    })
    public static class Quotes {

        protected List<SubscribeCommand.Quotes.Security> security;

        /**
         * Gets the value of the security property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the security property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubscribeCommand.Quotes.Security }
         * 
         * 
         */
        public List<SubscribeCommand.Quotes.Security> getSecurity() {
            if (security == null) {
                security = new ArrayList<SubscribeCommand.Quotes.Security>();
            }
            return this.security;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="board" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="seccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "board",
            "seccode"
        })
        public static class Security {

            @XmlElement(required = true)
            protected String board;
            @XmlElement(required = true)
            protected String seccode;

            /**
             * Gets the value of the board property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBoard() {
                return board;
            }

            /**
             * Sets the value of the board property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBoard(String value) {
                this.board = value;
            }

            /**
             * Gets the value of the seccode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeccode() {
                return seccode;
            }

            /**
             * Sets the value of the seccode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeccode(String value) {
                this.seccode = value;
            }

        }

    }

}
